//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PersonService.CalcService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcService.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CalcDiameter", ReplyAction="http://tempuri.org/ICalcService/CalcDiameterResponse")]
        double CalcDiameter(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CalcDiameter", ReplyAction="http://tempuri.org/ICalcService/CalcDiameterResponse")]
        System.Threading.Tasks.Task<double> CalcDiameterAsync(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CalcCircumference", ReplyAction="http://tempuri.org/ICalcService/CalcCircumferenceResponse")]
        double CalcCircumference(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CalcCircumference", ReplyAction="http://tempuri.org/ICalcService/CalcCircumferenceResponse")]
        System.Threading.Tasks.Task<double> CalcCircumferenceAsync(double radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : WPF_PersonService.CalcService.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<WPF_PersonService.CalcService.ICalcService>, WPF_PersonService.CalcService.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcDiameter(double radius) {
            return base.Channel.CalcDiameter(radius);
        }
        
        public System.Threading.Tasks.Task<double> CalcDiameterAsync(double radius) {
            return base.Channel.CalcDiameterAsync(radius);
        }
        
        public double CalcCircumference(double radius) {
            return base.Channel.CalcCircumference(radius);
        }
        
        public System.Threading.Tasks.Task<double> CalcCircumferenceAsync(double radius) {
            return base.Channel.CalcCircumferenceAsync(radius);
        }
    }
}
